name: OpenTX Commit Tests
on:
  push:
    branches: [ 2.3 ]
  pull_request:
    branches: [ 2.3 ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - COMPANION
          - X7
          - X9LITE
          - X9LITES
          - XLITE
          - XLITES
          - T12
          - TLITE
          - TX12
          - T8
          - X9D
          - X9DP
          - X9DP2019
          - TX16S
          - T16
          - T18
          - X10
          - X12S
    container:
      image: ghcr.io/raphaelcoeffic/opentx-commit-tests
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Test ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
        run: |
          echo "Running commit tests"
          ./tools/commit-tests.sh