name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '6-2017-q2'
      - uses: "CyberZHG/github-action-gtest@master"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip Pillow
      - name: CMake
        run: cmake .
      - name: make
        run: make
      - name: make tests
        run: make tests
